
from odoo import fields, models

class ImanautoGeneratedSno(models.Model):
    _inherit = 'stock.picking'
    #
    # # Add a custom field for the serial number
    serial_number = fields.Char('Serial Number', compute='_compute_serial_number', store=True)

    # Define a function to compute the serial number
    def _compute_serial_number(self):
        # print(self.name)
        for rec in self:
            # rec.serial_number= rec.name
            val=str(rec.name).split()
            print(val)
